UploadAndReadingExcelFile/UploadAndReadingExcelFile/Models/ErrorViewModel.cs
using System;

namespace UploadAndReadingExcelFile.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UploadAndReadingExcelFile/UploadAndReadingExcelFile/Models/Mentor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UploadAndReadingExcelFile.Models
{
    public class Mentor
    {
        public string Id { get; set; }
        public string Firstname { get; set; }

        public string Lastname { get; set; }
        public string OrganisationId { get; set; }
        public string EmailAddress { get; set; }

        public string ProfessionalNumber { get; set; }

        public string Position { get; set; }

        public string DateHired { get; set; }
    }
}

UploadAndReadingExcelFile/UploadAndReadingExcelFile/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using UploadAndReadingExcelFile.Models;

namespace UploadAndReadingExcelFile.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UploadAndReadingExcelFile/UploadAndReadingExcelFile/Controllers/MentorController.cs
using ExcelDataReader;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UploadAndReadingExcelFile.Models;

namespace UploadAndReadingExcelFile.Controllers
{
    public class MentorController : Controller
    {
        [HttpGet]
        public IActionResult Index(List<Mentor> mentors = null)
        {

            mentors = mentors == null ? new List<Mentor>() : mentors;

            return View(mentors);
        }

        [HttpPost]
        public IActionResult Index(IFormFile file, [FromServices] IHostingEnvironment hostingEnvironment)
        {
            string fileName = $"{hostingEnvironment.WebRootPath}\\files\\{file.FileName}";
            using (FileStream fileStream = System.IO.File.Create(fileName))
            {
                file.CopyTo(fileStream);
                fileStream.Flush();
            }
            var mentors = this.GetMentorList(file.FileName);
            return Index(mentors);
        }

        private List<Mentor> GetMentorList(string fName)
        {
            List<Mentor> mentors = new List<Mentor>();
            var fileName = $"{Directory.GetCurrentDirectory()}{@"\wwwroot\files"}" + "\\" + fName;
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            using (var stream = System.IO.File.Open(fileName, FileMode.Open, FileAccess.Read))
            {
                using (var reader = ExcelReaderFactory.CreateReader(stream))
                {
                    while (reader.Read())
                    {
                        mentors.Add(new Mentor()
                        {
                            Id = reader.GetValue(0).ToString(),
                            Position = reader.GetValue(1).ToString(),
                            DateHired = reader.GetValue(2).ToString(),
                            OrganisationId = reader.GetValue(3).ToString(),
                            Firstname = reader.GetValue(4).ToString(),
                            Lastname = reader.GetValue(5).ToString(),
                            EmailAddress = reader.GetValue(6).ToString(),
                            ProfessionalNumber = reader.GetValue(7).ToString(),
                      
                        });
                    }
                }
            }

            return mentors;

        }
    }
}

UploadAndReadingExcelFile/UploadAndReadingExcelFile/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UploadAndReadingExcelFile/UploadAndReadingExcelFile/Views/Mentor/Index.cshtml
@model IEnumerable<Mentor>

@{
    Layout = null;

}

<form asp-controller="Mentor" asp-action="Index" method="post" enctype="multipart/form-data">

    <input type="file" name="file" />
    <hr />
    <button type="submit">Upload</button>
</form>


@if (Model.Count() > 0)
{
    <hr />
    <table cellpadding="0" cellspacing="0" border="1">
        <tr>
            <th>Id</th>
            <th>DateHired</th>
            <th>EmailAddress</th>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Position</th>
            <th>ProfessionalNumber</th>
            <th>OrganisationId</th>
        </tr>
        @foreach (Mentor mentor in Model)
        {
            <tr>
                <td>@mentor.Id</td>
                <td>@mentor.DateHired</td>
                <td>@mentor.EmailAddress</td>
                <td>@mentor.Firstname</td>
                <td>@mentor.Lastname</td>
                <td>@mentor.Position</td>
                <td>@mentor.ProfessionalNumber</td>
                <td>@mentor.OrganisationId</td>
            </tr>
        }
    </table>
}

UploadAndReadingExcelFile/UploadAndReadingExcelFile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UploadAndReadingExcelFile</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UploadAndReadingExcelFile</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - UploadAndReadingExcelFile - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>